import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
await mkdir('docs/previews', { recursive: true });
const browser = await chromium.launch({ channel: 'msedge' });
const page = await browser.newPage({ viewport: { width: 1600, height: 1120 }, deviceScaleFactor: 1 });
await page.goto('http://127.0.0.1:5173');
await page.getByRole('heading', { name: '让工作，轻一点。' }).waitFor();
await page.screenshot({ path: 'docs/previews/workspace.png', fullPage: true, animations: 'disabled' });
await page.getByRole('button', { name: '展开 品牌设计 堆叠', exact: true }).click();
await page.getByRole('region', { name: '品牌设计 文件夹堆叠' }).waitFor();
await page.screenshot({ path: 'docs/previews/stack.png', fullPage: true, animations: 'disabled' });
await page.keyboard.press('Escape');
await page.getByRole('button', { name: '深色模式', exact: true }).click();
await page.screenshot({ path: 'docs/previews/dark.png', fullPage: true, animations: 'disabled' });
await page.setViewportSize({ width: 390, height: 844 });
await page.getByRole('button', { name: '浅色模式', exact: true }).click();
await page.evaluate(() => scrollTo(0,0));
await page.screenshot({ path: 'docs/previews/compact.png', fullPage: true, animations: 'disabled' });
await browser.close();
